"""Isolated host admission checks: no GitHub fixture or external command execution."""
import json
import os
import runpy
import subprocess
import sys
import tempfile
import tomllib
import unittest
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]


class HostContractTest(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.project = Path(self.temp.name)
        self.dispatch = runpy.run_path(str(ROOT / 'scripts/dispatch'))

    def install(self, version=None, *extra):
        command = [sys.executable, str(ROOT / 'scripts/install'), '--project', str(self.project)]
        if version is not None:
            command += ['--host-version', version]
        return subprocess.run(command + list(extra), capture_output=True, text=True, encoding='utf-8')

    def snapshot(self):
        return {str(p.relative_to(self.project)): p.read_bytes()
                for p in self.project.rglob('*') if p.is_file()}

    def test_installer_and_dispatcher_admit_each_explicit_known_host(self):
        for version, qualification in (('0.160.0', 'qualified'), ('0.160.1', 'candidate')):
            with self.subTest(version=version):
                result = self.install(version)
                self.assertEqual(result.returncode, 0, result.stderr)
                report = json.loads(result.stdout)
                self.assertEqual(report['host_version'], version)
                self.assertEqual(report.get('host_qualification'), qualification)
                self.assertIsNotNone(self.dispatch['qualify'](self.project, version))
                self.assertEqual(self.install(version, '--check').returncode, 0)

    def test_missing_and_unknown_observations_refuse_without_writes(self):
        self.assertEqual(self.install('0.160.0').returncode, 0)
        for version in (None, '', '0.159.2', '0.160.2', '0.161.0', 'codex-cli 0.160.1'):
            with self.subTest(version=version):
                before = self.snapshot()
                result = self.install(version)
                self.assertNotEqual(result.returncode, 0)
                with self.assertRaisesRegex(self.dispatch['Refusal'], 'host|Codex'):
                    self.dispatch['qualify'](self.project, version)
                self.assertEqual(self.snapshot(), before)

    def test_shared_roles_do_not_claim_an_observed_host_version(self):
        self.assertEqual(self.install('0.160.0').returncode, 0)
        before = self.snapshot()
        result = self.install('0.160.1')
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(self.snapshot(), before)
        for role in (self.project / '.codex/agents').glob('*.toml'):
            body = role.read_text(encoding='utf-8')
            self.assertNotIn('Codex 0.160.0 V2.', body.splitlines()[0])
            instructions = tomllib.loads(body)['developer_instructions']
            self.assertIn('0.160.1', instructions)

    def test_candidate_preserves_main_settings_and_unrelated_bytes(self):
        config = self.project / '.codex/config.toml'
        config.parent.mkdir()
        prior = ('# Keep 主会话 settings\nmodel = "main-model"\n'
                 'model_reasoning_effort = "xhigh"\nservice_tier = "fast"\n'
                 '[features]\nweb_search = true\n')
        config.write_text(prior, encoding='utf-8')
        before = config.read_bytes()
        result = self.install('0.160.1')
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertTrue(config.read_bytes().startswith(before))
        data = tomllib.loads(config.read_text(encoding='utf-8'))
        self.assertEqual(data['model'], 'main-model')
        self.assertEqual(data['model_reasoning_effort'], 'xhigh')
        self.assertEqual(data['service_tier'], 'fast')

    def test_candidate_upgrades_each_legacy_owned_marker_with_exact_backup(self):
        role = self.project / '.codex/agents/method_worker.toml'
        role.parent.mkdir(parents=True)
        for version in ('0.159.2', '0.160.0'):
            with self.subTest(previous_version=version):
                previous = (f'# Generated by codex-method scripts/install; Codex {version} V2.\n'
                            'name="method_worker"\ndescription="previous"\n'
                            'developer_instructions="previous"\n')
                role.write_text(previous, encoding='utf-8')
                before = role.read_bytes()
                result = self.install('0.160.1')
                self.assertEqual(result.returncode, 0, result.stderr)
                backups = [Path(p) for p in json.loads(result.stdout)['backups']]
                matching = [p for p in backups if p.name == role.name]
                self.assertEqual(len(matching), 1)
                self.assertEqual(matching[0].read_bytes(), before)
                self.assertNotIn(role.parent, matching[0].parents)

    def test_candidate_keeps_collision_refusal_before_any_write(self):
        role = self.project / '.codex/agents/method_worker.toml'
        role.parent.mkdir(parents=True)
        role.write_text('name="method_worker"\ndescription="mine"\n'
                        'developer_instructions="mine"\n', encoding='utf-8')
        before = self.snapshot()
        result = self.install('0.160.1')
        self.assertNotEqual(result.returncode, 0)
        self.assertIn('collision', result.stderr)
        self.assertEqual(self.snapshot(), before)

    def test_candidate_keeps_project_drift_visible_with_current_user_roles(self):
        self.assertEqual(self.install('0.160.0').returncode, 0)
        role = self.project / '.codex/agents/method_helper.toml'
        role.write_text(role.read_text(encoding='utf-8') + '\nmodel_verbosity="low"\n', encoding='utf-8')
        with patch.dict(os.environ, CODEX_HOME=str(self.project / 'user')):
            result = subprocess.run([sys.executable, str(ROOT / 'scripts/install'), '--user',
                                     '--host-version', '0.160.1'], capture_output=True,
                                    text=True, encoding='utf-8')
            self.assertEqual(result.returncode, 0, result.stderr)
            before = self.snapshot()
            with self.assertRaisesRegex(self.dispatch['Refusal'], 'stale|drift'):
                self.dispatch['qualify'](self.project, '0.160.1')
        self.assertEqual(self.snapshot(), before)
